version: 1.2
workflows:
- name: MalariaAssembly
  subclass: wdl
  primaryDescriptorPath: /wdl/MalariaAssembly.wdl
  testParameterFiles:
- name: ONT10x
  subclass: wdl
  primaryDescriptorPath: /wdl/ONT10x.wdl
  testParameterFiles:
- name: ONTWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/ONTWholeGenome.wdl
  testParameterFiles:
- name: ONTFlowcell
  subclass: wdl
  primaryDescriptorPath: /wdl/ONTFlowcell.wdl
  testParameterFiles:
- name: PBFlowcell
  subclass: wdl
  primaryDescriptorPath: /wdl/PBFlowcell.wdl
  testParameterFiles:
- name: PBCCS
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCCS.wdl
  testParameterFiles:
- name: PBCCSNoSharding
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCCSNoSharding.wdl
  testParameterFiles:
- name: PBCCS10x
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCCS10x.wdl
  testParameterFiles:
- name: PBCCSDemultiplex
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCCSDemultiplex.wdl
  testParameterFiles:
- name: PBCCSDemultiplexWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCCSDemultiplexWholeGenome.wdl
  testParameterFiles:
- name: PBCCSIsoSeq
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCCSIsoSeq.wdl
  testParameterFiles:
- name: PBCCSWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCCSWholeGenome.wdl
  testParameterFiles:
- name: PBCLRDemultiplexWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCLRDemultiplexWholeGenome.wdl
  testParameterFiles:
- name: PBCLRWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCLRWholeGenome.wdl
  testParameterFiles:
- name: ExtractAouData
  subclass: wdl
  primaryDescriptorPath: /wdl/ExtractAouData.wdl
  testParameterFiles:
- name: LRCNVs
  subclass: wdl
  primaryDescriptorPath: /wdl/LRCNVs.wdl
  testParameterFiles:
- name: ONTBasecall
  subclass: wdl
  primaryDescriptorPath: /wdl/ONTBasecall.wdl
  testParameterFiles:
- name: ONTAssembleWithCanu
  subclass: wdl
  primaryDescriptorPath: /wdl/ONTAssembleWithCanu.wdl
  testParameterFiles:
- name: ONTAssembleWithFlye
  subclass: wdl
  primaryDescriptorPath: /wdl/ONTAssembleWithFlye.wdl
  testParameterFiles:
- name: VerifyFingerprint
  subclass: wdl
  primaryDescriptorPath: /wdl/VerifyFingerprint.wdl
  testParameterFiles:
- name: DownloadFromHudsonAlpha
  subclass: wdl
  primaryDescriptorPath: /wdl/DownloadFromHudsonAlpha.wdl
  testParameterFiles:
- name: PBAssembleWithHifiasm
  subclass: wdl
  primaryDescriptorPath: /wdl/PBAssembleWithHifiasm.wdl
  testParameterFiles:
- name: ONTMethylation
  subclass: wdl
  primaryDescriptorPath: /wdl/ONTMethylation.wdl
  testParameterFiles:
- name: ONTPfHrp2Hrp3Status
  subclass: wdl
  primaryDescriptorPath: /wdl/ONTPfHrp2Hrp3Status.wdl
  testParameterFiles:
- name: ONTPfTypeDrugResistanceMarkers
  subclass: wdl
  primaryDescriptorPath: /wdl/ONTPfTypeDrugResistanceMarkers.wdl
  testParameterFiles:
