version: 1.2
workflows:
- name: MalariaAssembly
  subclass: wdl
  primaryDescriptorPath: /wdl/MalariaAssembly.wdl
  testParameterFiles:
- name: ONT10x
  subclass: wdl
  primaryDescriptorPath: /wdl/ONT10x.wdl
  testParameterFiles:
- name: ONTWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/ONTWholeGenome.wdl
  testParameterFiles:
- name: ONTFlowcell
  subclass: wdl
  primaryDescriptorPath: /wdl/ONTFlowcell.wdl
  testParameterFiles:
- name: PBFlowcell
  subclass: wdl
  primaryDescriptorPath: /wdl/PBFlowcell.wdl
  testParameterFiles:
- name: PBCCS
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCCS.wdl
  testParameterFiles:
- name: PBCCSNoSharding
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCCSNoSharding.wdl
  testParameterFiles:
- name: PBCCS10x
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCCS10x.wdl
  testParameterFiles:
- name: PBCCSDemultiplex
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCCSDemultiplex.wdl
  testParameterFiles:
- name: PBCCSDemultiplexWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCCSDemultiplexWholeGenome.wdl
  testParameterFiles:
- name: PBCCSIsoSeq
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCCSIsoSeq.wdl
  testParameterFiles:
- name: PBCCSWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCCSWholeGenome.wdl
  testParameterFiles:
- name: PBCLRDemultiplexWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCLRDemultiplexWholeGenome.wdl
  testParameterFiles:
- name: PBCLRWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/PBCLRWholeGenome.wdl
  testParameterFiles:
- name: ExtractAouData
  subclass: wdl
  primaryDescriptorPath: /wdl/ExtractAouData.wdl
  testParameterFiles:
- name: LRCNVs
  subclass: wdl
  primaryDescriptorPath: /wdl/LRCNVs.wdl
  testParameterFiles:
- name: ONTBasecall
  subclass: wdl
  primaryDescriptorPath: /wdl/ONTBasecall.wdl
  testParameterFiles:
- name: ONTAssembleWithCanu
  subclass: wdl
  primaryDescriptorPath: /wdl/ONTAssembleWithCanu.wdl
  testParameterFiles:
- name: ONTAssembleWithFlye
  subclass: wdl
  primaryDescriptorPath: /wdl/ONTAssembleWithFlye.wdl
  testParameterFiles:
- name: VerifyFingerprint
  subclass: wdl
  primaryDescriptorPath: /wdl/VerifyFingerprint.wdl
  testParameterFiles:
- name: CallTranslocator
  subclass: wdl
  primaryDescriptorPath: /wdl/CallTranslocator.wdl
  testParameterFiles:
- name: LocalAssembly
  subclass: wdl
  primaryDescriptorPath: /wdl/LocalAssembly.wdl
  testParameterFiles:
- name: LocalJointAssembly
  subclass: wdl
  primaryDescriptorPath: /wdl/LocalJointAssembly.wdl
  testParameterFiles:
- name: MergedAssemblyCanu
  subclass: wdl
  primaryDescriptorPath: /wdl/MergedAssemblyCanu.wdl
  testParameterFiles:
- name: BionanoAssemble
  subclass: wdl
  primaryDescriptorPath: /wdl/BionanoAssemble.wdl
  testParameterFiles:
- name: BionanoAlign
  subclass: wdl
  primaryDescriptorPath: /wdl/BionanoAlign.wdl
  testParameterFiles:
- name: Winnowmap
  subclass: wdl
  primaryDescriptorPath: /wdl/Winnowmap.wdl
  testParameterFiles:
- name: PBAssembleWithHifiasm
  subclass: wdl
  primaryDescriptorPath: /wdl/PBAssembleWithHifiasm.wdl
  testParameterFiles:
- name: LocalAssemblyHifiasmTrio
  subclass: wdl
  primaryDescriptorPath: /wdl/LocalAssemblyHifiasmTrio.wdl
  testParameterFiles:
- name: LocalAssemblyHifiasm
  subclass: wdl
  primaryDescriptorPath: /wdl/LocalAssemblyHifiasm.wdl
  testParameterFiles:
- name: LocalFast5Subset
  subclass: wdl
  primaryDescriptorPath: /wdl/LocalFast5Subset.wdl
  testParameterFiles:
- name: ONTMethylation
  subclass: wdl
  primaryDescriptorPath: /wdl/ONTMethylation.wdl
  testParameterFiles:
- name: Modbam2bed
  subclass: wdl
  primaryDescriptorPath: /wdl/Modbam2bed.wdl
  testParameterFiles:
- name: CallSniffles
  subclass: wdl
  primaryDescriptorPath: /wdl/CallSniffles.wdl
  testParameterFiles:
- name: ONTTelomereBasecaller
  subclass: wdl
  primaryDescriptorPath: /wdl/ONTTelomereBasecaller.wdl
  testParameterFiles:
- name: Minimap
  subclass: wdl
  primaryDescriptorPath: /wdl/Minimap.wdl
  testParameterFiles:
- name: Clipper
  subclass: wdl
  primaryDescriptorPath: /wdl/Clipper.wdl
  testParameterFiles:
- name: TTMarsEvaluateSVs
  subclass: wdl
  primaryDescriptorPath: /wdl/TTMarsEvaluateSVs.wdl
  testParameterFiles:
- name: LRMergeSVVCFs
  subclass: wdl
  primaryDescriptorPath: /wdl/LRMergeSVVCFs.wdl
  testParameterFiles:
- name: PALMER
  subclass: wdl
  primaryDescriptorPath: /wdl/PALMER.wdl
  testParameterFiles:
- name: xTea
  subclass: wdl
  primaryDescriptorPath: /wdl/xTea.wdl
  testParameterFiles:
- name: AlignedMetrics
  subclass: wdl
  primaryDescriptorPath: /wdl/tasks/SampleLevelAlignedMetrics.wdl
  testParameterFiles:
- name: SVAnnotate
  subclass: wdl
  primaryDescriptorPath: /wdl/SVAnnotate.wdl
  testParameterFiles:
- name: AnnotateVCFInsRM
  subclass: wdl
  primaryDescriptorPath: /wdl/AnnotateVCFInsRM.wdl
  testParameterFiles:
