version: 1.2
workflows:
- name: MalariaAssembly
  subclass: wdl
  primaryDescriptorPath: /wdl/MalariaAssembly.wdl
- name: ONT10x
  subclass: wdl
  primaryDescriptorPath: /deprecated_wdl/ONT10x.wdl
- name: ONTWholeGenome
  subclass: wdl
  primaryDescriptorPath: /pipelines/ONT/VariantCalling/ONTWholeGenome.wdl
- name: ONTFlowcell
  subclass: wdl
  primaryDescriptorPath: /pipelines/ONT/Preprocessing/ONTFlowcell.wdl
- name: PBFlowcell
  subclass: wdl
  primaryDescriptorPath: /pipelines/PacBio/Alignment/PBFlowcell.wdl
- name: PBCCS
  subclass: wdl
  primaryDescriptorPath: /deprecated_wdl/PBCCS.wdl
- name: PBCCS10x
  subclass: wdl
  primaryDescriptorPath: /deprecated_wdl/PBCCS10x.wdl
- name: PBCCSDemultiplex
  subclass: wdl
  primaryDescriptorPath: /deprecated_wdl/PBCCSDemultiplex.wdl
- name: PBCCSDemultiplexWholeGenome
  subclass: wdl
  primaryDescriptorPath: /deprecated_wdl/PBCCSDemultiplexWholeGenome.wdl
- name: PBCCSIsoSeq
  subclass: wdl
  primaryDescriptorPath: /pipelines/PacBio/Utility/PBCCSIsoSeq.wdl
- name: PBCCSWholeGenome
  subclass: wdl
  primaryDescriptorPath: /pipelines/PacBio/VariantCalling/PBCCSWholeGenome.wdl
- name: PBCLRDemultiplexWholeGenome
  subclass: wdl
  primaryDescriptorPath: /deprecated_wdl/PBCLRDemultiplexWholeGenome.wdl
- name: PBCLRWholeGenome
  subclass: wdl
  primaryDescriptorPath: /pipelines/PacBio/VariantCalling/PBCLRWholeGenome.wdl
- name: LRCNVs
  subclass: wdl
  primaryDescriptorPath: /pipelines/TechAgnostic/VariantCalling/LRCNVs.wdl
- name: ONTBasecall
  subclass: wdl
  primaryDescriptorPath: /pipelines/ONT/Preprocessing/ONTBasecall.wdl
- name: ONTAssembleWithCanu
  subclass: wdl
  primaryDescriptorPath: /pipelines/ONT/Assembly/ONTAssembleWithCanu.wdl
- name: ONTAssembleWithFlye
  subclass: wdl
  primaryDescriptorPath: /pipelines/ONT/Assembly/ONTAssembleWithFlye.wdl
- name: VerifyFingerprint
  subclass: wdl
  primaryDescriptorPath: /pipelines/TechAgnostic/Utility/VerifyFingerprint.wdl
- name: DownloadFromHudsonAlpha
  subclass: wdl
  primaryDescriptorPath: /deprecated_wdl/DownloadFromHudsonAlpha.wdl
- name: PBAssembleWithHifiasm
  subclass: wdl
  primaryDescriptorPath: /pipelines/PacBio/Assembly/PBAssembleWithHifiasm.wdl
- name: ONTMethylation
  subclass: wdl
  primaryDescriptorPath: /pipelines/ONT/Epigenomics/ONTMethylation.wdl
- name: ONTPfHrp2Hrp3Status
  subclass: wdl
  primaryDescriptorPath: /pipelines/ONT/MultiAnalysis/ONTPfHrp2Hrp3Status.wdl
- name: ONTPfTypeDrugResistanceMarkers
  subclass: wdl
  primaryDescriptorPath: /pipelines/ONT/MultiAnalysis/ONTPfTypeDrugResistanceMarkers.wdl
- name: PBMASIsoSeqQuantify
  subclass: wdl
  primaryDescriptorPath: /pipelines/PacBio/Utility/PBMASIsoSeqQuantify.wdl
- name: PBMASIsoSeqDemultiplex
  subclass: wdl
  primaryDescriptorPath: /pipelines/PacBio/Utility/PBMASIsoSeqDemultiplex.wdl
- name: LRJointCallGVCFs
  subclass: wdl
  primaryDescriptorPath: /pipelines/TechAgnostic/VariantCalling/LRJointCallGVCFs.wdl
- name: ConvertToHailMT
  subclass: wdl
  primaryDescriptorPath: /pipelines/TechAgnostic/Utility/ConvertToHailMT.wdl
- name: LRConvertBCF
  subclass: wdl
  primaryDescriptorPath: /pipelines/TechAgnostic/Utility/LRConvertBCF.wdl
