version: 1.2
workflows:
- name: ONT10x
  subclass: wdl
  primaryDescriptorPath: /wdl/deprecated/ONT10x.wdl
- name: ONTWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/VariantCalling/ONTWholeGenome.wdl
- name: ONTFlowcell
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/Preprocessing/ONTFlowcell.wdl
- name: PBFlowcell
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Alignment/PBFlowcell.wdl
- name: PBCCS
  subclass: wdl
  primaryDescriptorPath: /wdl/deprecated/PBCCS.wdl
- name: PBCCS10x
  subclass: wdl
  primaryDescriptorPath: /wdl/deprecated/PBCCS10x.wdl
- name: PBCCSDemultiplex
  subclass: wdl
  primaryDescriptorPath: /wdl/deprecated/PBCCSDemultiplex.wdl
- name: PBCCSDemultiplexWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/deprecated/PBCCSDemultiplexWholeGenome.wdl
- name: PBCCSIsoSeq
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Utility/PBCCSIsoSeq.wdl
- name: PBCCSWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/VariantCalling/PBCCSWholeGenome.wdl
- name: PBCLRDemultiplexWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/deprecated/PBCLRDemultiplexWholeGenome.wdl
- name: PBCLRWholeGenome
  subclass: wdl
  primaryDescriptorPath: /wdl/deprecated/PBCLRWholeGenome.wdl
- name: LRCNVs
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/VariantCalling/LRCNVs.wdl
- name: ONTBasecall
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/Preprocessing/ONTBasecall.wdl
- name: ONTAssembleWithCanu
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/Assembly/ONTAssembleWithCanu.wdl
- name: ONTAssembleWithFlye
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/Assembly/ONTAssembleWithFlye.wdl
- name: VerifyFingerprint
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/Utility/VerifyFingerprint.wdl
- name: DownloadFromHudsonAlpha
  subclass: wdl
  primaryDescriptorPath: /wdl/deprecated/DownloadFromHudsonAlpha.wdl
- name: PBAssembleWithHifiasm
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Assembly/PBAssembleWithHifiasm.wdl
- name: ONTMethylation
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/Epigenomics/ONTMethylation.wdl
- name: ONTPfHrp2Hrp3Status
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/MultiAnalysis/ONTPfHrp2Hrp3Status.wdl
- name: ONTPfTypeDrugResistanceMarkers
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/MultiAnalysis/ONTPfTypeDrugResistanceMarkers.wdl
- name: PBMASIsoSeqQuantify
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Utility/PBMASIsoSeqQuantify.wdl
- name: PBMASIsoSeqDemultiplex
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Utility/PBMASIsoSeqDemultiplex.wdl
- name: LRJointCallGVCFs
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/VariantCalling/LRJointCallGVCFs.wdl
- name: ConvertToHailMT
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/Utility/ConvertToHailMT.wdl
- name: LRConvertBCF
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/Utility/LRConvertBCF.wdl
- name: DownloadFromSRA
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/Utility/DownloadFromSRA.wdl
- name: DownloadFromWeb
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/Utility/DownloadFromWeb.wdl
- name: ONTProcessBasecall
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/Preprocessing/ONTProcessBasecall.wdl
- name: ONTFlowcellFromMultipleBasecalls
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/Preprocessing/ONTFlowcellFromMultipleBasecalls.wdl
- name: CleanupIntermediate
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/Utility/CleanupIntermediate.wdl
- name: HifiasmLocalAssembly
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Assembly/HifiasmLocalAssembly.wdl
- name: MitoHifiLocalAssembly
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Assembly/MitoHifiLocalAssembly.wdl
- name: SvimAsmAssemblyVariants
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/VariantCalling/SvimAsmAssemblyVariants.wdl
- name: HiCanuLocalAssembly
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Assembly/HiCanuLocalAssembly.wdl
- name: FlyeLocalAssembly
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Assembly/FlyeLocalAssembly.wdl
- name: Shapeit5
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Utility/Shapeit5.wdl
- name: PaftoolAsmVariants
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/VariantCalling/PaftoolAsmVariants.wdl
- name: WhatshapPhasing
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Assembly/WhatshapPhasing.wdl
- name: Bifrost
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Assembly/Bifrost.wdl
- name: JellyfishKmerCounting
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/KmerCounting/KmerCounting.wdl
- name: JellyfishKmerCountingPerSample
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/KmerCounting/KmerCountingPerSample.wdl
- name: JellyfishMergingKmerCount
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/TechAgnostic/KmerCounting/MergingKmercount.wdl
- name: ConsensusAsmFromShapeitScaffold
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Assembly/ConsensusAsmFromShapeitScaffold.wdl
- name: DeepSomatic
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/VariantCalling/DeepSomatic.wdl
- name: Spade_assembly
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Assembly/Spade_assembly.wdl
- name: HifiasmFullLengthContig
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Assembly/HifiasmFullLengthContig.wdl
- name: JointLocalAsmAnchorGraph
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Assembly/JointLocalAsmAnchorGraph.wdl
- name: JointLocalAsmAnchorGraph1
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Assembly/JointLocalAsmAnchorGraph1.wdl
- name: ImmunoAnnotate
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Assembly/ImmunoAnnotate.wdl
- name: AsmEvaluationDipcall
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/PacBio/Assembly/AsmEvaluationDipcall.wdl
- name: PbCpG
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/Epigenomics/PbCpG.wdl
- name: MethylArtist
  subclass: wdl
  primaryDescriptorPath: /wdl/pipelines/ONT/Epigenomics/Methylartist.wdl