version 1.0

workflow igv_screenshot_automation {

  input {
    File asm_hap1_bam   # BAM file for asm haplotype 1
    File asm_hap2_bam   # BAM file for asm haplotype 2
    File bam            # A single BAM file for the sample
    File reference_fasta  # Reference FASTA file
    File regions_bed      # Path to the BED file with regions of interest
    String genome         # Reference genome version (e.g., "hg38")
    Int image_height = 500  # Height for the IGV tracks
  }

  # Directly use .bam.bai files co-located with the BAM files
  call IGVScreenshotTask {
    input:
      asm_hap1_bam = asm_hap1_bam,
      asm_hap1_bai = asm_hap1_bam + ".bai",
      asm_hap2_bam = asm_hap2_bam,
      asm_hap2_bai = asm_hap2_bam + ".bai",
      bam = bam,
      bam_bai = bam + ".bai",
      reference_fasta = reference_fasta,
      regions_bed = regions_bed,
      genome = genome,
      image_height = image_height
  }

  output {
    Array[File] snapshots = IGVScreenshotTask.snapshots
  }
}

task IGVScreenshotTask {
  input {
    File asm_hap1_bam
    File asm_hap1_bai
    File asm_hap2_bam
    File asm_hap2_bai
    File bam
    File bam_bai
    File reference_fasta
    File regions_bed
    String genome
    Int image_height
  }

  command {
    # Localize the BAM and BAI files to ensure IGV can use them
    ln -s ${asm_hap1_bam} .
    ln -s ${asm_hap1_bai} .
    ln -s ${asm_hap2_bam} .
    ln -s ${asm_hap2_bai} .
    ln -s ${bam} .
    ln -s ${bam_bai} .

    # Run the Python script with inputs for asm_hap1, asm_hap2, and bam
    python3 /opt/IGV_Linux_2.18.2/make_igv_screenshot.py \
            ${asm_hap1_bam} ${asm_hap2_bam} ${bam} \
            -r ${regions_bed} -g ${genome} -ht ${image_height} \
            -ref_fasta ${reference_fasta} \
            -bin /opt/IGV_Linux_2.18.2/igv.sh
  }

  output {
    # Capture all the snapshot files generated by the script from the 'IGV_Snapshots' directory
    Array[File] snapshots = glob("IGV_Snapshots/*.png")
  }

  runtime {
    docker: "us.gcr.io/broad-dsp-lrma/igv_screenshot_docker:v982024"
    memory: "8G"
    cpu: 2
    disks: "local-disk 100 HDD"  # Adjust this based on file size needs
  }
}
