name: validate-wdls
on: push
jobs:
    publish-test:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout branch
              uses: actions/checkout@v3

            - name: Setup Java 11
              uses: actions/setup-java@v2
              with:
                distribution: 'temurin'
                java-version: '11'

            - name: Cache node_modules
              uses: actions/cache@v2
              with:
                path: "**/node_modules"
                key: ${{ runner.os }}-modules-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

            - name: Install dockstore cli
              run: |
                mkdir -p ~/bin
                curl -L -o ~/bin/dockstore https://github.com/dockstore/dockstore-cli/releases/download/1.13.1/dockstore
                chmod +x ~/bin/dockstore
                echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
                source ~/.bashrc

            - name: Validate dockstore.yml
              run: dockstore yaml validate --path .