name: validate-wdls
on: push
jobs:
    publish-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Cache node_modules
              uses: actions/cache@v2
              with:
                path: "**/node_modules"
                key: ${{ runner.os }}-modules-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                $CONDA/bin/conda install -y -c bioconda womtool
                echo "$CONDA/bin" >> $GITHUB_PATH

            # Validates all wdls in the pipeline and task folder. Would be useful in a
            # test that requries all wdls tested such as a monthly test
#            - name: Validate Pipelines
#              run: find ./pipelines -type f -name "*.wdl" | while read -r line ; do echo ${line}; womtool validate ${line}; done
#
#            - name: Validate Tasks
#              run: find ./tasks -type f -name "*.wdl" | while read -r line ; do echo ${line}; womtool validate ${line}; done

            - name: Validate All Edited WDLs
              run: git diff --name-only main | grep "\.wdl" | while read -r line ; do echo ${line}; womtool validate ${line}; done
