name: Build and deploy site to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install Requirments
        run: |
          python -m pip install --upgrade pip
          pip install wdldoc

      - name: Create documents
        run: wdldoc -v --debug -o ./docs ./wdl/*

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: bs_add_docs
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: docs/
